name: Optimized Recursive Update of PR Stack on Squash Merge

on:
  pull_request:
    types: [closed]

permissions:
  contents: write
  pull-requests: write
  repository-projects: read # See https://github.com/cli/cli/discussions/5307

jobs:
  update-pr-stack:
    if: github.event.pull_request.merged == true && github.event.pull_request.merge_commit_sha != ''
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Update PR stack
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
